select * from customer limit 5

-- Q1. What is the total revenue generated by male vs female customers?

select gender, sum(purchase_amount) as revenue
from customer
group by(gender)

-- Q2 Which customers used a discount but still spent more than the average purchase amount?

select customer_id, purchase_amount
from customer
where 
discount_applied = 'Yes' 
and
purchase_amount >= (
select AVG(purchase_amount) 
from customer
)

-- Q3 Which are the top 5 products with the highest average review rating?

select item_purchased as "Product", round(AVG(review_rating::numeric),2) as "AVG review rating"
from customer
group by item_purchased
order by AVG(review_rating) desc
limit 5;

--Q4 Compare the average purchase amounts between standard and express shipping.

select shipping_type, round(AVG(purchase_amount),3) as "AVG purchases"
from customer
where shipping_type in ('Express','Standard')
group by shipping_type
order by "AVG purchases" desc

-- Q5. Do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status, ROUND(avg(purchase_amount),2)as "AVG Revenue", sum(purchase_amount) as "Total Revenue"
from customer
group by subscription_status
order by "AVG Revenue" desc

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, (sum(case when discount_applied = 'Yes' then 1 else 0 end))*100/count(*) as "Percent",count(*)
from customer
group by item_purchased
order by "Percent" desc
limit 5;

-- Q7. Segment customers into new, returning, and loyal based on their total number of previous purchases, 
-- and show the amount of each segment.

with customer_type as (
select customer_id, previous_purchases,
case
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer
)

select customer_segment,count(*) as "Number of customers"
from customer_type
group by customer_segment

-- Q8. What are the top 3 most purchased products within each category?

with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also like to subscribe?

select subscription_status, count(customer_id) as "repeat_customers"
from customer
where previous_purchases > 5
group by subscription_status

-- Q10. What is the revenue contribution of each age group?

select age_group, sum(purchase_amount)
from customer
group by age_group
order by sum(purchase_amount) desc
